### ISSUE TITLE
Exchange rate missing reference if localstorage is deleted

### ISSUE THREAD

**Issue by cyrilcero** [cyrilcero/Banking-App#24]
Bug: Exchange rate missing reference if localstorage is deleted
Page/Component: exchangerate.jsx
Assigned to:
Status: (pending, working on, complete)

**Comment by jeanevabejar** [comment]
me na dito

**Comment by jeanevabejar** [comment]
ayos na toh pacheck na lang. i tried to put spinner din if ever na magload although di ko sure yung sizing ng spinner kasi makikita lang sya if ever na hindi nag instant fetch

**Comment by jeanevabejar** [comment]
ayos na toh pacheck na lang. i tried to put spinner din if ever na magload although di ko sure yung sizing ng spinner kasi makikita lang sya if ever na hindi nag instant fetch
