### ISSUE TITLE
admin create account password 

### ISSUE THREAD

**Issue by jeanevabejar** [cyrilcero/Banking-App#26]
Bug: lumalabas yung validation ng password na dapat 6 character sya.  although ang clinick pa lang yung firstname input and wala pang submission

Page/Component:
Assigned to:
Status: (pending, working on, complete)

**Comment by louisedungca** [comment]
also for pw validation: "pw is less than 6 char..." still showing even when char=6 na

**Comment by cyrilcero** [comment]
Hindi ko po pala sinama logic nyan para maging successful yung account creation, for some reason hindi 1:1 yung pagbibilang sa input kaya bugged yung error message?

**Comment by louisedungca** [comment]
specific issue for password character error validation fixed.
