### ISSUE TITLE
Admin Transfer Money - Cash in History after transferring money

### ISSUE THREAD

**Issue by cyrilcero** [cyrilcero/Banking-App#62]
![image](https://github.com/cyrilcero/Banking-App/assets/40516714/ab465d8d-9c7b-47f6-bbb8-4767151c5f2f)

need to push new objects to CashInHistory localStorage for both sender/receiver. 

```
      history.push(newHistory);
      setLocalStorage("CashInHistory", history);
```

**Comment by jeanevabejar** [comment]
di ko gets sir Cy??

**Comment by jeanevabejar** [comment]
resolved
